In [ ]:
import pandas as pd

In [ ]:
price_df = pd.read_csv("/content/price_data (1).csv")

In [ ]:
price_df.head()

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.0,0.0,44.266931,0.0,0.0
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.0,0.0,44.266931,0.0,0.0
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.0,0.0,44.266931,0.0,0.0
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.0,0.0,44.266931,0.0,0.0
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.0,0.0,44.266931,0.0,0.0

In [ ]:
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193002 entries, 0 to 193001
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  193002 non-null  object
 1   price_date          193002 non-null  object
 2   price_off_peak_var  193002 non-null  float64
 3   price_peak_var      193002 non-null  float64
 4   price_mid_peak_var  193002 non-null  float64
 5   price_off_peak_fix  193002 non-null  float64
 6   price_peak_fix      193002 non-null  float64
 7   price_mid_peak_fix  193002 non-null  float64
dtypes: float64(6), object(2)
memory usage: 11.8+ MB

In [ ]:
price_df.describe()

,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
count,193002.000000,193002.000000,193002.000000,193002.000000,193002.000000,193002.000000
mean,0.141027,0.054630,0.030496,43.334477,10.622875,6.409984
std,0.025032,0.049924,0.036298,5.410297,12.841895,7.773592
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.125976,0.000000,0.000000,40.728885,0.000000,0.000000
50%,0.146033,0.085483,0.000000,44.266930,0.000000,0.000000
75%,0.151635,0.101673,0.072558,44.444710,24.339581,16.226389
max,0.280700,0.229788,0.114102,59.444710,36.490692,17.458221

In [ ]:
price_df.isnull().sum()

id                    0
price_date            0
price_off_peak_var    0
price_peak_var        0
price_mid_peak_var    0
price_off_peak_fix    0
price_peak_fix        0
price_mid_peak_fix    0
dtype: int64

In [ ]:
price_df.columns

Index(['id', 'price_date', 'price_off_peak_var', 'price_peak_var',
       'price_mid_peak_var', 'price_off_peak_fix', 'price_peak_fix',
       'price_mid_peak_fix'],
      dtype='object')

In [ ]:
price_df['id'].duplicated().sum()

np.int64(176906)

In [ ]:
price_df['id'].value_counts().head()

id
c18b6305122e4976739b8420d5b54ec5    12
e4053a0ad6c55e4665e8e9adb9f75db5    12
1221993f581c1b335d231e247028d40d    12
2dc2c9a9f6e6896d9a07d7bcbb9d0ce9    12
762cab733464cae4ce1d452ce84cb94b    12
Name: count, dtype: int64

In [ ]:
price_df['price_date'].min()
price_df['price_date'].max()

'2015-12-01'

In [ ]:
price_df['id'].nunique()

16096

In [ ]:
price_df.shape

(193002, 8)

In [ ]:
price_df['price_date'].value_counts().sort_index().head()

price_date
2015-01-01    16070
2015-02-01    16082
2015-03-01    16074
2015-04-01    16079
2015-05-01    16080
Name: count, dtype: int64

In [ ]:
price_df['price_date'].value_counts().sort_index().tail()

price_date
2015-08-01    16094
2015-09-01    16082
2015-10-01    16085
2015-11-01    16087
2015-12-01    16094
Name: count, dtype: int64

In [ ]:
price_df['id'].isin(client_df['id']).sum()

np.int64(175149)

In [ ]:
price_df.groupby('id').size().describe()

count    16096.000000
mean        11.990681
std          0.137117
min          7.000000
25%         12.000000
50%         12.000000
75%         12.000000
max         12.000000
dtype: float64

In [ ]:
client_df = pd.read_csv("/content/client_data (1).csv")

In [ ]:
client_df.head()

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,t,0.00,25.44,25.44,2,678.99,3,lxidpiddsbxsbosboudacockeimpuepw,43.648,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,f,0.00,16.38,16.38,1,18.89,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.800,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,f,0.00,28.60,28.60,1,6.60,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.856,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,f,0.00,30.22,30.22,1,25.46,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,f,52.32,44.91,44.91,1,47.98,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,19.800,0

In [ ]:
client_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14606 non-null  object
 1   channel_sales                   14606 non-null  object
 2   cons_12m                        14606 non-null  int64
 3   cons_gas_12m                    14606 non-null  int64
 4   cons_last_month                 14606 non-null  int64
 5   date_activ                      14606 non-null  object
 6   date_end                        14606 non-null  object
 7   date_modif_prod                 14606 non-null  object
 8   date_renewal                    14606 non-null  object
 9   forecast_cons_12m               14606 non-null  float64
 10  forecast_cons_year              14606 non-null  int64
 11  forecast_discount_energy        14606 non-null  float64
 12  forecast_meter_rent_12m         14606 non-null  float64
 13  forecast_price_energy_off_peak  14606 non-null  float64
 14  forecast_price_energy_peak      14606 non-null  float64
 15  forecast_price_pow_off_peak     14606 non-null  float64
 16  has_gas                         14606 non-null  object
 17  imp_cons                        14606 non-null  float64
 18  margin_gross_pow_ele            14606 non-null  float64
 19  margin_net_pow_ele              14606 non-null  float64
 20  nb_prod_act                     14606 non-null  int64
 21  net_margin                      14606 non-null  float64
 22  num_years_antig                 14606 non-null  int64
 23  origin_up                       14606 non-null  object
 24  pow_max                         14606 non-null  float64
 25  churn                           14606 non-null  int64
dtypes: float64(11), int64(7), object(8)
memory usage: 2.9+ MB

In [ ]:
client_df.describe()

,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,forecast_price_pow_off_peak,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,pow_max,churn
count,1.460600e+04,1.460600e+04,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000,14606.000000
mean,1.592203e+05,2.809238e+04,16090.269752,1868.614880,1399.762906,0.966726,63.086871,0.137283,0.050491,43.130056,152.786896,24.565121,24.562517,1.292346,189.264522,4.997809,18.135136,0.097152
std,5.734653e+05,1.629731e+05,64364.196422,2387.571531,3247.786255,5.108289,66.165783,0.024623,0.049037,4.485988,341.369366,20.231172,20.230280,0.709774,311.798130,1.611749,13.534743,0.296175
min,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,3.300000,0.000000
25%,5.674750e+03,0.000000e+00,0.000000,494.995000,0.000000,0.000000,16.180000,0.116340,0.000000,40.606701,0.000000,14.280000,14.280000,1.000000,50.712500,4.000000,12.500000,0.000000
50%,1.411550e+04,0.000000e+00,792.500000,1112.875000,314.000000,0.000000,18.795000,0.143166,0.084138,44.311378,37.395000,21.640000,21.640000,1.000000,112.530000,5.000000,13.856000,0.000000
75%,4.076375e+04,0.000000e+00,3383.000000,2401.790000,1745.750000,0.000000,131.030000,0.146348,0.098837,44.311378,193.980000,29.880000,29.880000,1.000000,243.097500,6.000000,19.172500,0.000000
max,6.207104e+06,4.154590e+06,771203.000000,82902.830000,175375.000000,30.000000,599.310000,0.273963,0.195975,59.266378,15042.790000,374.640000,374.640000,32.000000,24570.650000,13.000000,320.000000,1.000000

In [ ]:
client_df.isnull().sum()

id                                0
channel_sales                     0
cons_12m                          0
cons_gas_12m                      0
cons_last_month                   0
date_activ                        0
date_end                          0
date_modif_prod                   0
date_renewal                      0
forecast_cons_12m                 0
forecast_cons_year                0
forecast_discount_energy          0
forecast_meter_rent_12m           0
forecast_price_energy_off_peak    0
forecast_price_energy_peak        0
forecast_price_pow_off_peak       0
has_gas                           0
imp_cons                          0
margin_gross_pow_ele              0
margin_net_pow_ele                0
nb_prod_act                       0
net_margin                        0
num_years_antig                   0
origin_up                         0
pow_max                           0
churn                             0
dtype: int64

In [ ]:
client_df.columns

Index(['id', 'channel_sales', 'cons_12m', 'cons_gas_12m', 'cons_last_month',
       'date_activ', 'date_end', 'date_modif_prod', 'date_renewal',
       'forecast_cons_12m', 'forecast_cons_year', 'forecast_discount_energy',
       'forecast_meter_rent_12m', 'forecast_price_energy_off_peak',
       'forecast_price_energy_peak', 'forecast_price_pow_off_peak', 'has_gas',
       'imp_cons', 'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'num_years_antig', 'origin_up', 'pow_max', 'churn'],
      dtype='object')

In [ ]:
client_df['id'].duplicated().sum()

np.int64(0)

In [ ]:
client_df.shape

(14606, 26)

In [ ]:
client_df['id'].isin(price_df['id']).sum()

np.int64(14606)

In [ ]:
client_df['churn'].value_counts()

churn
0    13187
1     1419
Name: count, dtype: int64

In [ ]:
client_df.groupby('churn').mean(numeric_only=True)

,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,forecast_price_pow_off_peak,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,pow_max
churn,,,,,,,,,,,,,,,,,
0,167867.266550,30121.497308,17046.352089,1858.473333,1402.487601,0.938197,62.126588,0.137371,0.050019,43.108310,152.964184,23.929863,23.926979,1.295822,185.057407,5.037006,18.000339
1,78862.478506,9235.411557,7205.239605,1962.861938,1374.441860,1.231853,72.010937,0.136470,0.054873,43.332143,151.139331,30.468682,30.468682,1.260042,228.361938,4.633545,19.387827

In [ ]:
client_df.groupby('churn').mean(numeric_only=True).T

churn                                       0             1
cons_12m                        167867.266550  78862.478506
cons_gas_12m                     30121.497308   9235.411557
cons_last_month                  17046.352089   7205.239605
forecast_cons_12m                 1858.473333   1962.861938
forecast_cons_year                1402.487601   1374.441860
forecast_discount_energy             0.938197      1.231853
forecast_meter_rent_12m             62.126588     72.010937
forecast_price_energy_off_peak       0.137371      0.136470
forecast_price_energy_peak           0.050019      0.054873
forecast_price_pow_off_peak         43.108310     43.332143
imp_cons                           152.964184    151.139331
margin_gross_pow_ele                23.929863     30.468682
margin_net_pow_ele                  23.926979     30.468682
nb_prod_act                          1.295822      1.260042
net_margin                         185.057407    228.361938
num_years_antig                      5.037006      4.633545
pow_max                             18.000339     19.387827

In [ ]:
client_df['id'].nunique()

14606

In [ ]:
price_summary = \
price_df.groupby('id').agg({
    'price_off_peak_var': 'mean',
    'price_peak_var': 'mean',
    'price_mid_peak_var': 'mean',
    'price_off_peak_fix': 'mean',
    'price_peak_fix': 'mean',
    'price_mid_peak_fix': 'mean'
}).reset_index()

In [ ]:
price_summary.head().T

,0,1,2,3,4
id,0002203ffbb812588b632b9e628cc38d,0004351ebdd665e6ee664792efc4fd13,0010bcc39e42b3c2131ed2ce55246e3c,0010ee3855fdea87602a5b7aba8e42de,00114d74e963e47177db89bc70108537
price_off_peak_var,0.124338,0.146426,0.181558,0.118757,0.147926
price_peak_var,0.103794,0.0,0.0,0.098292,0.0
price_mid_peak_var,0.07316,0.0,0.0,0.069032,0.0
price_off_peak_fix,40.701732,44.38545,45.31971,40.647427,44.26693
price_peak_fix,24.421038,0.0,0.0,24.388455,0.0
price_mid_peak_fix,16.280694,0.0,0.0,16.258971,0.0

In [ ]:
df = client_df.merge(price_summary, on='id', how='left')
df.shape

(14606, 32)

In [ ]:
df.isnull().sum()

id                                0
channel_sales                     0
cons_12m                          0
cons_gas_12m                      0
cons_last_month                   0
date_activ                        0
date_end                          0
date_modif_prod                   0
date_renewal                      0
forecast_cons_12m                 0
forecast_cons_year                0
forecast_discount_energy          0
forecast_meter_rent_12m           0
forecast_price_energy_off_peak    0
forecast_price_energy_peak        0
forecast_price_pow_off_peak       0
has_gas                           0
imp_cons                          0
margin_gross_pow_ele              0
margin_net_pow_ele                0
nb_prod_act                       0
net_margin                        0
num_years_antig                   0
origin_up                         0
pow_max                           0
churn                             0
price_off_peak_var                0
price_peak_var                    0
price_mid_peak_var                0
price_off_peak_fix                0
price_peak_fix                    0
price_mid_peak_fix                0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)].shape

(0, 32)

In [ ]:
price_cols = [
    'price_off_peak_var',
    'price_peak_var',
    'price_mid_peak_var',
    'price_off_peak_fix',
    'price_peak_fix',
    'price_mid_peak_fix'
]
df[price_cols] = df[price_cols].fillna(df[price_cols].median())

In [ ]:
for col in ['channel_sales', 'origin_up', 'has_gas']:
  print(f"\n--- {col} ---")
  print(df.groupby(col)
  ['churn'].agg(['mean', 'count']).sort_values('mean', ascending=False))

--- channel_sales ---
                                      mean  count
channel_sales
foosdfpfkusacimwkcsosbicdxkicaua  0.121410   6754
usilxuppasemubllopkaafesmlibmsdf  0.100364   1375
ewpakwlliwisiwduibdlfmalxowmwpci  0.083987    893
MISSING                           0.075973   3725
lmkebamcaaclubfxadlmueccxoimlema  0.055887   1843
epumfxlbckeskwekxbiuasklxalciiuu  0.000000      3
fixdbufsefwooaasfcxdxadsiekoceaa  0.000000      2
sddiedcslfslkckwlfkdpoeeailfpeds  0.000000     11

--- origin_up ---
                                      mean  count
origin_up
lxidpiddsbxsbosboudacockeimpuepw  0.125828   7097
ldkssxwpmemidmecebumciepifcamkci  0.083863   3148
MISSING                           0.062500     64
kamkkxfxxuwbdslkwifmmcsiusiuosws  0.060084   4294
ewxeelcelemmiwuafmddpobolfuxioce  0.000000      1
usapbepcfoloekilkwsdiboslwaxobdp  0.000000      2

--- has_gas ---
             mean  count
has_gas
f        0.100544  11955
t        0.081856   2651